# Generated by Django 2.1.2 on 2018-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20181011_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='动作名')),
                ('conditions', models.TextField(verbose_name='告警条件')),
                ('interval', models.IntegerField(default=300, verbose_name='告警间隔(s)')),
                ('recover_notice', models.BooleanField(default=True, verbose_name='故障恢复后发送通知消息')),
                ('recover_subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='故障恢复后通知主题')),
                ('recover_message', models.TextField(blank=True, null=True, verbose_name='故障恢复后通知消息')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否开启')),
            ],
        ),
        migrations.CreateModel(
            name='ActionOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='动作操作名')),
                ('step', models.SmallIntegerField(default=1, verbose_name='第n次告警')),
                ('action_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('script', 'RunScript')], max_length=64, verbose_name='动作类型')),
                ('msg_format', models.TextField(default='Host({hostname},{ip}) service({service_name}) has issue,msg:{msg}', verbose_name='消息格式')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='monitor.HostGroup', verbose_name='主机组名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor.Template', verbose_name='模板名'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor.Template', verbose_name='模板名'),
        ),
        migrations.AlterField(
            model_name='service',
            name='has_sub_service',
            field=models.BooleanField(default=False, verbose_name='是否有子服务'),
        ),
        migrations.AlterField(
            model_name='serviceindex',
            name='key',
            field=models.CharField(max_length=64, verbose_name='指标'),
        ),
        migrations.AlterField(
            model_name='serviceindex',
            name='name',
            field=models.CharField(max_length=64, verbose_name='监控项'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否开启'),
        ),
        migrations.AddField(
            model_name='action',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='monitor.HostGroup', verbose_name='主机组'),
        ),
        migrations.AddField(
            model_name='action',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='monitor.Host', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(to='monitor.ActionOperation', verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='action',
            name='triggers',
            field=models.ManyToManyField(blank=True, help_text='想让哪些trigger触发当前报警动作', to='monitor.Trigger', verbose_name='触发器'),
        ),
    ]
